A-OKVQA:
    dataset_parser: distill_mmeb
    dataset_name: TIGER-Lab/MMEB-train
    subset_name: A-OKVQA
    dataset_split: original
    image_dir: vlm2vec_train/MMEB-train
    num_sample_per_subset: 20000
    weight: 1
ChartQA:
    dataset_parser: distill_mmeb
    dataset_name: TIGER-Lab/MMEB-train
    subset_name: ChartQA
    dataset_split: original
    image_dir: vlm2vec_train/MMEB-train
    num_sample_per_subset: 28000
    weight: 1
CIRR:
    dataset_parser: distill_mmeb
    dataset_name: TIGER-Lab/MMEB-train
    subset_name: CIRR
    dataset_split: original
    image_dir: vlm2vec_train/MMEB-train
    num_sample_per_subset: 30000
    weight: 1
